version: "3.5"
services:
  php_fpm:
      build: .
      container_name: vue_php_fpm
      working_dir: /usr/share/nginx/vue
      networks:
        - vue
      volumes:
          - ./:/usr/share/nginx/vue
  nginx:
      image: nginx:1.15
      container_name: vue_nginx
      working_dir: /usr/share/nginx/vue
      networks:
        - vue
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/vue
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf


networks:
  vue:
    driver: bridge
